

dataset_path: I:/wirenet_dateset

#train parameters
num_classes: 2
num_keypoints: 2
opt: 'adamw'
batch_size: 2
epochs: 10
lr: 0.005
momentum: 0.9
weight_decay: 0.0001
lr_step_size: 3
lr_gamma: 0.1
num_workers: 4
print_freq: 10
target_type: pixel
enable_logs: True
augmentation: False
checkpoint: None


## Classes
#names:
#  0: fire
#  1: dust
#  2: move_machine
#  3: open_machine
#  4: close_machine


