

# Train/val/val sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
dataset_path: F:\DevTools\datasets\renyaun\1012\spilt
#train: images/train  # train images (relative to 'path') 128 images
#val: images/train  # val images (relative to 'path') 128 images
#val: images/val  # val images (optional)

#train parameters
num_classes: 5
opt: 'adamw'
batch_size: 2
epochs: 10
lr: 0.005
momentum: 0.9
weight_decay: 0.0001
lr_step_size: 3
lr_gamma: 0.1
num_workers: 4
print_freq: 10
target_type: polygon
enable_logs: True
augmentation: True


## Classes
#names:
#  0: fire
#  1: dust
#  2: move_machine
#  3: open_machine
#  4: close_machine


